### ISSUE TITLE
Propfind information from MSDN

### ISSUE THREAD

**Issue by snapo** [mikea/gdrive-webdav#2]
Hi and thanks very much for this great work.....
https://msdn.microsoft.com/en-us/library/aa142960%28v=exchg.65%29.aspx
This URL will help you with more information on the PROPFIND information that microsofts native webdav client uses as option.

I really like this project and its also working and compiling under ubuntu 14.04

UPDATE: seems that microsoft has a bug in his webdav client that it does not respond correctly. http://lists.w3.org/Archives/Public/public-html/2011Jan/0263.html
Seems that the way arround is to force the XML answer

Great job man ;=)

**Comment by mikea** [comment]
Props are fully implemented now.
