### ISSUE TITLE
Google Authorization Error

### ISSUE THREAD

**Issue by liberix** [mikea/gdrive-webdav#7]
Hi, nice project firstly,

When I try to run the docker with client_id and client_secret generated by Google Cloud, a url showed in prompt as:
```
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=<client_id>&redirect_uri=<>&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state-token
``` 
And the Authorization Error Page showed up:

![image](https://user-images.githubusercontent.com/68191508/172753587-2b090edf-fb58-48d1-9e58-14a2c96eb163.png)

Is there any way to fix this? Thanks!

**Comment by seba5496** [comment]
I found a [similar issue in rclone](https://forum.rclone.org/t/google-drive-oauth-with-non-interactive-no-longer-works/29626), with their wrokflow for Oauth, it has something to do with a OOB workflow being deprecated. [Link to Github issue for more details on this.](https://github.com/rclone/rclone/issues/6000)
Searching on the internet [i found that](https://stackoverflow.com/questions/19706562/how-to-handle-urnietfwgoauth2-0oob-redirect-in-google-calendar-api-authoriz) it would be better to use a service account from google, but unfortunately i don’t know this programming language (Go) to modify this behavior.
Maybe @mikea could help?

**Comment by mikea** [comment]
You should now request Desktop Application credentials, not Web App. I have updated the README file. I just tried the process yesterday and it seems to work.
